!===============================================================================




! ADAPTER: UFRIC — ABAQUS UFRIC → UFC Native Interface
! Auto-generated by gen_umat_adapter.py — DO NOT EDIT MANUALLY
! Template: umat_adapter.f90.j2
! Reference: ABAQUS_Subroutine_UFC_TYPE_Mapping.md §6
! Generated: 2026-04-13T15:30:33Z
!
! PURPOSE:
!   ABAQUS UFRIC flat-parameter interface
!     → pack into UFC TYPE structures
!     → call UFC native interface (PH_Cont_UFRIC_API)
!     → unpack results back to ABAQUS flat arrays
!
! DESIGN RULES (Principle #14 / SIO):
!   [*] Flat arrays ONLY in this adapter -- never in UFC native code
!   [*] All ABAQUS params packed into Desc/State/Algo/Ctx TYPEs
!   [*] UFC native side uses typed structs exclusively
!   [*] Thin adapter: pure glue, no physics logic here
!
! USAGE:
!   1. Copy generated file to: UFC/ufc_core/L4_PH/Contact/Adapters/
!   2. Rename UFRIC → UFRIC (keep ABAQUS ABI signature)
!   3. USE UFC native module: USE PH_Cont_UFRIC_Mod
!   4. Build once at model load → call PH_Cont_UFRIC_API at each material point
!
! PARAMETER MAP (from UFC mapping doc):
!   TFRIC        -> state%fric_stress                       [OUT]
!   STATF        -> state%statev(1:nstatv)                  [OUT]
!   TIME         -> ctx%step_time/ctx%total_time            [IN]
!   SLIP         -> ctx%slip_magnitude                      [IN]
!   SPRESS       -> ctx%contact_pressure                    [IN]
!   TEMP         -> ctx%temp                                [IN]
!   NOEL         -> ctx%elem_id                             [IN]
!   NPT          -> ctx%pt_id                               [IN]
!   PROPS        -> desc%props(1:nprops)                    [IN]
!   NPROPS       -> desc%nprops                             [IN]
!   NTENS        -> algo%ntens                              [IN]
!   STATEV       -> state%statev(1:nstatv)                  [IN/OUT]
!   NSTATV       -> algo%nstatv                             [IN]
!   SNAME        -> desc%fric_name                          [IN]
!   KSTEP        -> ctx%kstep                               [IN]
!   KINC         -> ctx%kinc                                [IN]
!===============================================================================
MODULE PH_Cont_UFRIC_Adapter_Mod
  USE IF_Prec_Core,     ONLY: wp, i4
  !-- UFC native TYPEs (L3_MD layer — model description)
  USE MD_Mat_Types, ONLY: &
    MD_Mat_Base_Desc,  &  ! Material parameter base (props, model_name)
    MD_Mat_Base_State, &  ! Material state base (stress, statev, ddsdde)
    MD_Mat_Base_Algo       ! Pre-analysis config (ntens, ndi, nshr, nstatv)
  !-- UFC native TYPEs (L4_PH layer — physical compute)
  USE PH_Mat_Types, ONLY: &
    PH_Mat_Base_Ctx,   &  ! Per-increment driving inputs
    PH_Mat_Base_Algo       ! Newton iteration control
  !-- UFC native TYPEs (L5_RT layer — runtime bookkeeping)
  USE RT_Com_Types, ONLY: RT_Com_Base_Ctx
  !-- UFC native module (replace with actual model module)
  ! USE PH_Cont_UFRIC_Mod, ONLY: PH_Cont_UFRIC_API
  IMPLICIT NONE
  PRIVATE

  PUBLIC :: UFRIC

CONTAINS

  !============================================================================
  ! UFRIC — ABAQUS UFRIC Interface Adapter
  !
  ! This adapter is the SOLE entry point for ABAQUS UFRIC calls.
  ! It handles ONLY parameter packing/unpacking — all physics lives in
  ! PH_Cont_UFRIC_API (called via UFC native interface).
  !
  ! Calling sequence:
  !   [ABAQUS] → UFRIC(flat params)
  !            → pack → UFC TYPE structs
  !            → PH_Cont_UFRIC_API(typed structs)
  !            → unpack → flat arrays
  !            → [ABAQUS]
  !============================================================================
  SUBROUTINE UFRIC( &
    TFRIC       , &
    STATF        (*), &
    TIME         (*), &
    SLIP        , &
    SPRESS      , &
    TEMP        , &
    NOEL        , &
    NPT         , &
    PROPS        (*), &
    NPROPS      , &
    NTENS       , &
    STATEV       (*), &
    NSTATV      , &
    SNAME       , &
    KSTEP       , &
    KINC        , &

    )
    !-- Declarations (keep ABAQUS ABI names)
    REAL(wp), INTENT(OUT) :: TFRIC
    REAL(wp), INTENT(OUT) :: STATF(*)
    REAL(wp), INTENT(IN) :: TIME(*)
    REAL(wp), INTENT(IN) :: SLIP
    REAL(wp), INTENT(IN) :: SPRESS
    REAL(wp), INTENT(IN) :: TEMP
    INTEGER(i4), INTENT(IN) :: NOEL
    INTEGER(i4), INTENT(IN) :: NPT
    REAL(wp), INTENT(IN) :: PROPS(*)
    INTEGER(i4), INTENT(IN) :: NPROPS
    INTEGER(i4), INTENT(IN) :: NTENS
    REAL(wp), INTENT(INOUT) :: STATEV(*)
    INTEGER(i4), INTENT(IN) :: NSTATV
    CHARACTER(LEN=80), INTENT(IN) :: SNAME
    INTEGER(i4), INTENT(IN) :: KSTEP
    INTEGER(i4), INTENT(IN) :: KINC


    !-- Local UFC TYPE instances (stack-allocated, no heap allocation)
    TYPE(MD_Mat_Base_Desc)  :: desc
    TYPE(MD_Mat_Base_State) :: state
    TYPE(MD_Mat_Base_Algo)  :: algo
    TYPE(PH_Mat_Base_Ctx)   :: ctx
    TYPE(RT_Com_Base_Ctx)   :: rt_ctx
    REAL(wp) :: pnewdt_buf

    !-- Local scalar buffers
    INTEGER(i4) :: kstep_local, kinc_local
    REAL(wp) :: step_time_local, total_time_local

    !---------------------------------------------------------------------------
    ! STEP 1: Pack ABAQUS parameters → UFC TYPE structures
    !---------------------------------------------------------------------------

    !-- [IN] Desc: material parameters (read-only, built at model load)
    desc%model_name       = cmname
    IF (ALLOCATED(desc%props)) DEALLOCATE(desc%props)
    ALLOCATE(desc%props(nprops))
    desc%props(1:nprops)  = props(1:nprops)
    desc%nprops            = nprops

    !-- [IN] Algo: pre-analysis solver configuration
    algo%ndi              = ndi
    algo%nshr             = nshr
    algo%ntens            = ntens
    algo%nstatv           = nstatv
    algo%integ_scheme     = 1_i4     ! implicit (UMAT default)
    algo%compute_tangent  = .TRUE.
    algo%use_algorithmic  = .FALSE.

    !-- [IN/OUT] State: material point state (updated in-place)
    state%stress(1:ntens)           = stress(1:ntens)
    state%statev(1:nstatv)          = statev(1:nstatv)
    state%ddsdde(1:ntens,1:ntens)   = ddsdde(1:ntens,1:ntens)
    state%sse = sse;  state%spd = spd;  state%scd = scd
    state%rpl  = rpl

    !-- [IN] Ctx: per-increment driving inputs
    ctx%stran(1:ntens)    = stran(1:ntens)
    ctx%dstran(1:ntens)   = dstran(1:ntens)
    step_time_local        = time(1)
    total_time_local       = time(2)
    ctx%step_time          = step_time_local
    ctx%total_time         = total_time_local
    ctx%dtime             = dtime
    ctx%temp              = temp
    ctx%dtemp             = dtemp
    ctx%coords(1:3)       = coords(1:3)
    ctx%drot(1:3,1:3)     = drot(1:3,1:3)
    ctx%celent            = celent
    ctx%dfgrd0(1:3,1:3)  = dfgrd0(1:3,1:3)
    ctx%dfgrd1(1:3,1:3)  = dfgrd1(1:3,1:3)
    kstep_local            = kstep
    kinc_local             = kinc
    ctx%kstep             = kstep_local
    ctx%kinc              = kinc_local
    ctx%elem_id           = noel
    ctx%gauss_pt          = npt
    ctx%layer             = layer
    ctx%kspt              = kspt

    !-- [RT] Runtime context
    rt_ctx%step_time      = step_time_local
    rt_ctx%total_time     = total_time_local
    rt_ctx%dtime          = dtime
    rt_ctx%kstep          = kstep_local
    rt_ctx%kinc           = kinc_local
    rt_ctx%elem_id        = noel
    rt_ctx%nlgeom         = (DFGRD0(1,1) /= 1.0_wp .OR. &
                               DFGRD0(2,2) /= 1.0_wp .OR. &
                               DFGRD0(3,3) /= 1.0_wp)
    rt_ctx%first_increment = (kinc == 1_i4)

    !-- pnewdt buffer
    pnewdt_buf = 1.0_wp  ! RT_PNEWDT_NO_CHANGE

    !---------------------------------------------------------------------------
    ! STEP 2: Call UFC native interface (replace with actual model call)
    !---------------------------------------------------------------------------
    ! CALL PH_Cont_UFRIC_API(desc, ctx, state, algo, pnewdt_buf)
    ! Stub: replace with actual UFC native call when model is implemented
    ! Example:
    !   USE PH_Cont_UFRIC_Mod, ONLY: PH_Cont_UFRIC_API
    !   CALL PH_Cont_UFRIC_API(desc, ctx, state, algo, rt_ctx, pnewdt_buf)

    !---------------------------------------------------------------------------
    ! STEP 3: Unpack UFC TYPE structures → ABAQUS flat arrays
    !---------------------------------------------------------------------------

    !-- [OUT] State → flat arrays
    stress(1:ntens)               = state%stress(1:ntens)
    statev(1:nstatv)              = state%statev(1:nstatv)
    ddsdde(1:ntens,1:ntens)       = state%ddsdde(1:ntens,1:ntens)
    sse  = state%sse;  spd = state%spd;  scd = state%scd
    rpl  = state%rpl
    ddsddt(1:ntens)               = state%ddsddt(1:ntens)
    drplde(1:ntens)               = state%drplde(1:ntens)
    drpldt                        = state%drpldt
    pnewdt                        = pnewdt_buf

  END SUBROUTINE UFRIC

END MODULE PH_Cont_UFRIC_Adapter_Mod
