!===============================================================================
! MODULE: PH_L4_L3MatContract
! LAYER:  L4_PH
! DOMAIN: Material / Bridge
! BRIEF:  L3 **class_id** → L4 **PH_MAT_*** mapping + default discrete **MAT_*** ids.
!===============================================================================
MODULE PH_L4_L3MatContract
  USE IF_Prec_Core, ONLY: i4
  USE MD_Mat_Def, ONLY: &
    MD_MAT_CATEGORY_EL, MD_MAT_CATEGORY_PL, MD_MAT_CATEGORY_DA, MD_MAT_CATEGORY_HY, &
    MD_MAT_CATEGORY_VI, MD_MAT_CATEGORY_CR, MD_MAT_CATEGORY_CO, MD_MAT_CATEGORY_US, &
    MD_MAT_CATEGORY_GEOMAT, MD_MAT_CATEGORY_COMPOSITE, MD_MAT_CATEGORY_MULTIPHYS
  USE MD_Mat_Ids, ONLY: &
    MAT_PLAST_J2_ISO, MAT_GEO_DP_LINEAR, MAT_COMP_CLT, MAT_HEAT_ISO
  USE PH_Mat_Enum, ONLY: &
    PH_MAT_UNKNOWN, PH_MAT_ELASTIC, PH_MAT_ELASTO_PLASTIC, PH_MAT_HYPERELASTIC, &
    PH_MAT_VISCOELASTIC, PH_MAT_CREEP, PH_MAT_DAMAGE, PH_MAT_GEOTECH, &
    PH_MAT_COMPOSITE, PH_MAT_THERMAL, PH_MAT_ACOUSTIC, PH_MAT_USER
  IMPLICIT NONE
  PRIVATE

  INTEGER(i4), PARAMETER, PUBLIC :: MAT_ID_PLASTIC_DEFAULT = MAT_PLAST_J2_ISO
  INTEGER(i4), PARAMETER, PUBLIC :: MAT_ID_GEOTECH_DEFAULT = MAT_GEO_DP_LINEAR
  INTEGER(i4), PARAMETER, PUBLIC :: MAT_ID_COMPOSITE_DEFAULT = MAT_COMP_CLT
  INTEGER(i4), PARAMETER, PUBLIC :: MAT_ID_THERMAL_DEFAULT = MAT_HEAT_ISO

  PUBLIC :: PH_MapL3MatTypeToL4
  PUBLIC :: PH_MapL3ClassToDefaultMatId

CONTAINS

  PURE FUNCTION PH_MapL3MatTypeToL4(class_id) RESULT(ph_marker)
    INTEGER(i4), INTENT(IN) :: class_id
    INTEGER(i4) :: ph_marker

    SELECT CASE (class_id)
    CASE (MD_MAT_CATEGORY_EL)
      ph_marker = PH_MAT_ELASTIC
    CASE (MD_MAT_CATEGORY_PL)
      ph_marker = PH_MAT_ELASTO_PLASTIC
    CASE (MD_MAT_CATEGORY_DA)
      ph_marker = PH_MAT_DAMAGE
    CASE (MD_MAT_CATEGORY_HY)
      ph_marker = PH_MAT_HYPERELASTIC
    CASE (MD_MAT_CATEGORY_VI)
      ph_marker = PH_MAT_VISCOELASTIC
    CASE (MD_MAT_CATEGORY_CR)
      ph_marker = PH_MAT_CREEP
    CASE (MD_MAT_CATEGORY_CO)
      ph_marker = PH_MAT_COMPOSITE
    CASE (MD_MAT_CATEGORY_US)
      ph_marker = PH_MAT_USER
    CASE (MD_MAT_CATEGORY_GEOMAT)
      ph_marker = PH_MAT_GEOTECH
    CASE (MD_MAT_CATEGORY_COMPOSITE)
      ph_marker = PH_MAT_COMPOSITE
    CASE (MD_MAT_CATEGORY_MULTIPHYS)
      ph_marker = PH_MAT_THERMAL
    CASE DEFAULT
      ph_marker = PH_MAT_UNKNOWN
    END SELECT
  END FUNCTION PH_MapL3MatTypeToL4

  PURE FUNCTION PH_MapL3ClassToDefaultMatId(class_id) RESULT(mid)
    INTEGER(i4), INTENT(IN) :: class_id
    INTEGER(i4) :: mid

    SELECT CASE (class_id)
    CASE (MD_MAT_CATEGORY_PL)
      mid = MAT_ID_PLASTIC_DEFAULT
    CASE (MD_MAT_CATEGORY_GEOMAT)
      mid = MAT_ID_GEOTECH_DEFAULT
    CASE (MD_MAT_CATEGORY_COMPOSITE)
      mid = MAT_ID_COMPOSITE_DEFAULT
    CASE (MD_MAT_CATEGORY_MULTIPHYS)
      mid = MAT_ID_THERMAL_DEFAULT
    CASE DEFAULT
      mid = 0_i4
    END SELECT
  END FUNCTION PH_MapL3ClassToDefaultMatId

END MODULE PH_L4_L3MatContract
