!===============================================================================
! MODULE: PH_Cont_ThermoMech
! LAYER:  L4_PH
! DOMAIN: Contact / Thermal
! ROLE:   Core
! BRIEF:  Thermo-mechanical coupled contact (heat flux, conductance, friction heating)
!
! Theory: q = h_c*(T_s-T_m); Q_fric = mu*|F_n|*|v_slip|
!   Wriggers §13; Jaeger (1942); Barber (2003)
! Contract: L4_PH/Contact/CONTRACT.md
! Status: ACTIVE | Last verified: 2026-04-28
!===============================================================================
MODULE PH_Cont_ThermoMech
  USE IF_Base_Def, ONLY: ZERO, ONE, TWO, SMALL_VAL => SMALL
  USE IF_Err_Brg, ONLY: ErrorStatusType, init_error_status, IF_STATUS_OK, IF_STATUS_INVALID
  USE IF_Prec_Core, ONLY: wp, i4
  
  IMPLICIT NONE
  PRIVATE
  
  ! ===================================================================
  ! Public Types
  ! ===================================================================
  PUBLIC :: PH_ContTH_Pair
  PUBLIC :: PH_ContTH_ConductanceLaw
  PUBLIC :: PH_ContTH_FrictionHeat
  
  ! ===================================================================
  ! Public Interfaces
  ! ===================================================================
  PUBLIC :: PH_ContTH_ComputeHeatFlux
  PUBLIC :: PH_ContTH_ComputeConductance
  PUBLIC :: PH_ContTH_ComputeFrictionHeat
  PUBLIC :: PH_ContTH_UpdateTemperature
  PUBLIC :: PH_ContTH_CoupledResponse
  PUBLIC :: PH_ContTH_Compute_ContactHeatFlux
  
  ! ===================================================================
  ! Type Definitions
  ! ===================================================================
  
  TYPE :: PH_ContTH_Pair
    ! Thermo-mechanical contact pair
    INTEGER(i4) :: pair_id
    REAL(wp) :: mechanical_gap      ! Mechanical gap
    REAL(wp) :: mechanical_pressure ! Contact pressure
    REAL(wp) :: temp_slave          ! Temperature on slave side
    REAL(wp) :: temp_master         ! Temperature on master side
    REAL(wp) :: heat_flux           ! Heat flux across interface
    REAL(wp) :: conductance         ! Thermal contact conductance
    REAL(wp) :: friction_heat       ! Heat generated by friction
    LOGICAL :: is_active            ! Active contact flag
  END TYPE PH_ContTH_Pair
  
  TYPE :: PH_ContTH_ConductanceLaw
    ! Thermal contact conductance model
    INTEGER(i4) :: law_type    ! 1=Linear, 2=Power, 3=Exponential
    REAL(wp) :: param_a        ! Model parameter A
    REAL(wp) :: param_b        ! Model parameter B
    REAL(wp) :: param_c        ! Model parameter C
    CHARACTER(LEN=32) :: name  ! Model name
  CONTAINS
    PROCEDURE :: Evaluate => ConductanceLaw_Evaluate
  END TYPE PH_ContTH_ConductanceLaw
  
  TYPE :: PH_ContTH_FrictionHeat
    ! Frictional heating parameters
    REAL(wp) :: friction_coeff     ! Friction coefficient μ
    REAL(wp) :: slip_velocity(3)   ! Relative slip velocity
    REAL(wp) :: heat_partition     ! Heat partition factor [0,1]
    REAL(wp) :: flash_temp         ! Flash temperature rise
    LOGICAL :: use_flash           ! Enable flash temperature calculation
  END TYPE PH_ContTH_FrictionHeat
  
CONTAINS

  ! ===========================================================================
  ! Heat Flux Computation
  ! ===========================================================================
  
  SUBROUTINE PH_ContTH_ComputeHeatFlux(pair, status)
    !> Compute heat flux across contact interface: q = h_c * ΔT
    TYPE(PH_ContTH_Pair), INTENT(INOUT) :: pair
    TYPE(ErrorStatusType), INTENT(OUT), OPTIONAL :: status
    
    REAL(wp) :: delta_temp
    
    IF (PRESENT(status)) CALL init_error_status(status)
    
    IF (.NOT. pair%is_active) THEN
      pair%heat_flux = ZERO
      IF (PRESENT(status)) status%status_code = IF_STATUS_OK
      RETURN
    END IF
    
    ! Temperature difference
    delta_temp = pair%temp_slave - pair%temp_master
    
    ! Heat flux: q = h_c * (T_s - T_m)
    pair%heat_flux = pair%conductance * delta_temp
    
    IF (PRESENT(status)) status%status_code = IF_STATUS_OK
  END SUBROUTINE PH_ContTH_ComputeHeatFlux
  
  ! ===========================================================================
  ! Contact Conductance Models
  ! ===========================================================================
  
  FUNCTION ConductanceLaw_Evaluate(this, pressure, gap, temp_avg) RESULT(h_c)
    !> Evaluate thermal contact conductance
    CLASS(PH_ContTH_ConductanceLaw), INTENT(IN) :: this
    REAL(wp), INTENT(IN) :: pressure, gap, temp_avg
    REAL(wp) :: h_c
    
    SELECT CASE(this%law_type)
    CASE(1_i4)  ! Linear: h_c = a + b*p
      h_c = this%param_a + this%param_b * MAX(ZERO, pressure)
      
    CASE(2_i4)  ! Power: h_c = a * p^b
      h_c = this%param_a * MAX(pressure, SMALL_VAL)**this%param_b
      
    CASE(3_i4)  ! Exponential with gap: h_c = a * exp(-b*g)
      h_c = this%param_a * EXP(-this%param_b * MAX(ZERO, gap))
      
    CASE DEFAULT
      h_c = this%param_a
    END SELECT
  END FUNCTION ConductanceLaw_Evaluate
  
  SUBROUTINE PH_ContTH_ComputeConductance(pair, law, roughness, status)
    !> Compute thermal contact conductance based on pressure and roughness
    TYPE(PH_ContTH_Pair), INTENT(INOUT) :: pair
    TYPE(PH_ContTH_ConductanceLaw), INTENT(IN) :: law
    REAL(wp), INTENT(IN) :: roughness
    TYPE(ErrorStatusType), INTENT(OUT), OPTIONAL :: status
    
    REAL(wp) :: temp_avg
    
    IF (PRESENT(status)) CALL init_error_status(status)
    
    ! Average temperature
    temp_avg = HALF * (pair%temp_slave + pair%temp_master)
    
    ! Evaluate conductance law
    pair%conductance = law%Evaluate(pair%mechanical_pressure, &
                                    pair%mechanical_gap, temp_avg)
    
    ! Roughness correction (simplified)
    IF (roughness > ZERO) THEN
      pair%conductance = pair%conductance / (ONE + roughness * 1000.0_wp)
    END IF
    
    IF (PRESENT(status)) status%status_code = IF_STATUS_OK
  END SUBROUTINE PH_ContTH_ComputeConductance
  
  ! ===========================================================================
  ! Frictional Heating
  ! ===========================================================================
  
  SUBROUTINE PH_ContTH_ComputeFrictionHeat(pair, friction, normal_force, status)
    !> Compute frictional heating: Q = μ * |F_n| * |v_slip|
    TYPE(PH_ContTH_Pair), INTENT(INOUT) :: pair
    TYPE(PH_ContTH_FrictionHeat), INTENT(IN) :: friction
    REAL(wp), INTENT(IN) :: normal_force
    TYPE(ErrorStatusType), INTENT(OUT), OPTIONAL :: status
    
    REAL(wp) :: slip_speed, power
    
    IF (PRESENT(status)) CALL init_error_status(status)
    
    ! Slip speed
    slip_speed = SQRT(SUM(friction%slip_velocity**2))
    
    ! Frictional power: P = μ * F_n * v_slip
    power = friction%friction_coeff * ABS(normal_force) * slip_speed
    
    ! Heat generation (all power converted to heat)
    pair%friction_heat = power
    
    ! Flash temperature (simplified Jaeger solution)
    IF (friction%use_flash) THEN
      ! ΔT_flash = Q / (2*k*A)
      ! Placeholder: would need thermal conductivity k and contact area A
      pair%flash_temp = power / (TWO * 1.0_wp * 1.0e-6_wp)  ! Simplified
    END IF
    
    IF (PRESENT(status)) status%status_code = IF_STATUS_OK
  END SUBROUTINE PH_ContTH_ComputeFrictionHeat
  
  ! ===========================================================================
  ! Coupled Thermo-Mechanical Response
  ! ===========================================================================
  
  SUBROUTINE PH_ContTH_CoupledResponse(pairs, n_pairs, law, friction, &
                                       coords, temps, F_mech, Q_thermal, status)
    !> Fully coupled thermo-mechanical contact response
    TYPE(PH_ContTH_Pair), INTENT(INOUT) :: pairs(:)
    INTEGER(i4), INTENT(IN) :: n_pairs
    TYPE(PH_ContTH_ConductanceLaw), INTENT(IN) :: law
    TYPE(PH_ContTH_FrictionHeat), INTENT(IN) :: friction
    REAL(wp), INTENT(IN) :: coords(:,:)
    REAL(wp), INTENT(IN) :: temps(:)
    REAL(wp), INTENT(OUT) :: F_mech(:)
    REAL(wp), INTENT(OUT) :: Q_thermal(:)
    TYPE(ErrorStatusType), INTENT(OUT), OPTIONAL :: status
    
    INTEGER(i4) :: i_pair, i_node, j_node
    REAL(wp) :: normal_force, heat_flux, temp_diff
    
    IF (PRESENT(status)) CALL init_error_status(status)
    
    ! Initialize outputs
    F_mech = ZERO
    Q_thermal = ZERO
    
    ! Process each pair
    DO i_pair = 1, n_pairs
      IF (.NOT. pairs(i_pair)%is_active) CYCLE
      
      ! Update temperatures from global field
      i_node = pairs(i_pair)%pair_id  ! Assuming pair_id maps to node
      j_node = i_node + 1             ! Simplified
      
      pairs(i_pair)%temp_slave = temps(i_node)
      pairs(i_pair)%temp_master = temps(j_node)
      
      ! Compute conductance
      CALL PH_ContTH_ComputeConductance(pairs(i_pair), law, 0.0_wp, status)
      
      ! Compute heat flux
      CALL PH_ContTH_ComputeHeatFlux(pairs(i_pair), status)
      
      ! Compute frictional heating
      CALL PH_ContTH_ComputeFrictionHeat(pairs(i_pair), friction, &
                                         pairs(i_pair)%mechanical_pressure, status)
      
      ! Assemble thermal load
      heat_flux = pairs(i_pair)%heat_flux + pairs(i_pair)%friction_heat
      Q_thermal(i_node) = Q_thermal(i_node) + heat_flux
      Q_thermal(j_node) = Q_thermal(j_node) - heat_flux
      
    END DO
    
    IF (PRESENT(status)) status%status_code = IF_STATUS_OK
  END SUBROUTINE PH_ContTH_CoupledResponse

  ! ===========================================================================
  ! Temperature Update (Forward Euler)
  ! ===========================================================================

  SUBROUTINE PH_ContTH_UpdateTemperature(pair, dt, capacity_slave, capacity_master, status)
    !> Update interface temperatures based on heat flux and time step
    TYPE(PH_ContTH_Pair), INTENT(INOUT) :: pair
    REAL(wp), INTENT(IN) :: dt               ! Time step
    REAL(wp), INTENT(IN) :: capacity_slave   ! Slave heat capacity [J/(K*m^2)]
    REAL(wp), INTENT(IN) :: capacity_master  ! Master heat capacity [J/(K*m^2)]
    TYPE(ErrorStatusType), INTENT(OUT), OPTIONAL :: status

    IF (PRESENT(status)) CALL init_error_status(status)

    IF (.NOT. pair%is_active) THEN
      IF (PRESENT(status)) status%status_code = IF_STATUS_OK
      RETURN
    END IF

    ! Forward Euler: T_new = T_old +/- (q / c) * dt
    IF (capacity_slave > SMALL_VAL) THEN
      pair%temp_slave = pair%temp_slave - &
        (pair%heat_flux + pair%friction_heat * HALF) / capacity_slave * dt
    END IF
    IF (capacity_master > SMALL_VAL) THEN
      pair%temp_master = pair%temp_master + &
        (pair%heat_flux - pair%friction_heat * HALF) / capacity_master * dt
    END IF

    IF (PRESENT(status)) status%status_code = IF_STATUS_OK
  END SUBROUTINE PH_ContTH_UpdateTemperature

  ! ===========================================================================
  ! Standalone Contact Heat Flux with Gap-Dependent Conductance
  ! ===========================================================================

  SUBROUTINE PH_ContTH_Compute_ContactHeatFlux(gap_n, T_slave, T_master, &
                                                h_contact, q, dq_dTs, dq_dTm, ierr)
    !> Compute contact heat flux with gap-dependent conductance:
    !>   - In contact (gap_n <= 0): q = h_cond * (T_slave - T_master)
    !>   - Separated (gap_n > 0):   q = h_gap / gap_n * (T_slave - T_master)
    !> Also returns derivatives for coupled Newton iterations.
    REAL(wp), INTENT(IN)     :: gap_n          ! Normal gap (>0 open, <0 contact)
    REAL(wp), INTENT(IN)     :: T_slave        ! Slave temperature [K]
    REAL(wp), INTENT(IN)     :: T_master       ! Master temperature [K]
    REAL(wp), INTENT(IN)     :: h_contact      ! Contact conductance / gap conductivity
    REAL(wp), INTENT(OUT)    :: q              ! Heat flux [W/m^2]
    REAL(wp), INTENT(OUT)    :: dq_dTs         ! dq/dT_slave
    REAL(wp), INTENT(OUT)    :: dq_dTm         ! dq/dT_master
    INTEGER(i4), INTENT(OUT) :: ierr

    REAL(wp) :: h_eff, delta_T

    ierr = 0
    delta_T = T_slave - T_master

    IF (gap_n <= ZERO) THEN
      ! In contact: direct thermal conductance
      h_eff = h_contact
    ELSE
      ! Separated: gap-dependent (h_eff = k_gap / gap)
      IF (gap_n > SMALL_VAL) THEN
        h_eff = h_contact / gap_n
      ELSE
        h_eff = h_contact / SMALL_VAL
      END IF
    END IF

    ! Heat flux: q = h_eff * (T_slave - T_master)
    q = h_eff * delta_T

    ! Derivatives for coupled solution
    dq_dTs =  h_eff
    dq_dTm = -h_eff

  END SUBROUTINE PH_ContTH_Compute_ContactHeatFlux

END MODULE PH_Cont_ThermoMech