!===============================================================================




! ADAPTER: UMAT — ABAQUS UMAT → UFC Native Interface
! Auto-generated by gen_umat_adapter.py — DO NOT EDIT MANUALLY
! Template: umat_adapter.f90.j2
! Reference: ABAQUS_Subroutine_UFC_TYPE_Mapping.md §2
! Generated: 2026-04-13T15:30:33Z
!
! PURPOSE:
!   ABAQUS UMAT flat-parameter interface
!     → pack into UFC TYPE structures
!     → call UFC native interface (PH_Mat_UMAT_API)
!     → unpack results back to ABAQUS flat arrays
!
! DESIGN RULES (Principle #14 / SIO):
!   [*] Flat arrays ONLY in this adapter -- never in UFC native code
!   [*] All ABAQUS params packed into Desc/State/Algo/Ctx TYPEs
!   [*] UFC native side uses typed structs exclusively
!   [*] Thin adapter: pure glue, no physics logic here
!
! USAGE:
!   1. Copy generated file to: UFC/ufc_core/L4_PH/Material/Adapters/
!   2. Rename UMAT → UMAT (keep ABAQUS ABI signature)
!   3. USE UFC native module: USE PH_Mat_UMAT_Mod
!   4. Build once at model load → call PH_Mat_UMAT_API at each material point
!
! PARAMETER MAP (from UFC mapping doc):
!   STRESS       -> state%stress(1:ntens)                   [IN/OUT]
!   STATEV       -> state%statev(1:nstatv)                  [IN/OUT]
!   DDSDDE       -> state%ddsdde(1:ntens,1:ntens)           [OUT]
!   SSE          -> state%sse                               [IN/OUT]
!   SPD          -> state%spd                               [IN/OUT]
!   SCD          -> state%scd                               [IN/OUT]
!   RPL          -> state%rpl                               [IN/OUT]
!   DDSDDT       -> state%ddsddt(1:ntens)                   [OUT]
!   DRPLDE       -> state%drplde(1:ntens)                   [OUT]
!   DRPLDT       -> state%drpldt                            [OUT]
!   STRAN        -> ctx%stran(1:ntens)                      [IN]
!   DSTRAN       -> ctx%dstran(1:ntens)                     [IN]
!   TIME         -> ctx%step_time/ctx%total_time            [IN]
!   DTIME        -> ctx%dtime                               [IN]
!   TEMP         -> ctx%temp                                [IN]
!   DTEMP        -> ctx%dtemp                               [IN]
!   PREDEF       -> ctx%predef(1:npredf)                    [IN]
!   DPRED        -> ctx%dpred(1:npredf)                     [IN]
!   CMNAME       -> desc%model_name                         [IN]
!   NDI          -> algo%ndi                                [IN]
!   NSHR         -> algo%nshr                               [IN]
!   NTENS        -> algo%ntens                              [IN]
!   NSTATV       -> algo%nstatv                             [IN]
!   NPROPS       -> desc%nprops                             [IN]
!   PROPS        -> desc%props(1:nprops)                    [IN]
!   COORDS       -> ctx%coords(1:3)                         [IN]
!   DROT         -> ctx%drot(1:3,1:3)                       [IN]
!   PNEWDT       -> state%pnewdt                            [OUT]
!   CELENT       -> ctx%celent                              [IN]
!   DFGRD0       -> ctx%dfgrd0(1:3,1:3)                     [IN]
!   DFGRD1       -> ctx%dfgrd1(1:3,1:3)                     [IN]
!   NOEL         -> ctx%elem_id                             [IN]
!   NPT          -> ctx%gauss_pt                            [IN]
!   LAYER        -> ctx%layer                               [IN]
!   KSPT         -> ctx%kspt                                [IN]
!   KSTEP        -> ctx%kstep                               [IN]
!   KINC         -> ctx%kinc                                [IN]
!===============================================================================
MODULE PH_Mat_UMAT_Adapter_Mod
  USE IF_Prec_Core,     ONLY: wp, i4
  !-- UFC native TYPEs (L3_MD layer — model description)
  USE MD_Mat_Types, ONLY: &
    MD_Mat_Base_Desc,  &  ! Material parameter base (props, model_name)
    MD_Mat_Base_State, &  ! Material state base (stress, statev, ddsdde)
    MD_Mat_Base_Algo       ! Pre-analysis config (ntens, ndi, nshr, nstatv)
  !-- UFC native TYPEs (L4_PH layer — physical compute)
  USE PH_Mat_Types, ONLY: &
    PH_Mat_Base_Ctx,   &  ! Per-increment driving inputs
    PH_Mat_Base_Algo       ! Newton iteration control
  !-- UFC native TYPEs (L5_RT layer — runtime bookkeeping)
  USE RT_Com_Types, ONLY: RT_Com_Base_Ctx
  !-- UFC native module (replace with actual model module)
  ! USE PH_Mat_UMAT_Mod, ONLY: PH_Mat_UMAT_API
  IMPLICIT NONE
  PRIVATE

  PUBLIC :: UMAT

CONTAINS

  !============================================================================
  ! UMAT — ABAQUS UMAT Interface Adapter
  !
  ! This adapter is the SOLE entry point for ABAQUS UMAT calls.
  ! It handles ONLY parameter packing/unpacking — all physics lives in
  ! PH_Mat_UMAT_API (called via UFC native interface).
  !
  ! Calling sequence:
  !   [ABAQUS] → UMAT(flat params)
  !            → pack → UFC TYPE structs
  !            → PH_Mat_UMAT_API(typed structs)
  !            → unpack → flat arrays
  !            → [ABAQUS]
  !============================================================================
  SUBROUTINE UMAT( &
    STRESS       (*), &
    STATEV       (*), &
    DDSDDE       (*), &
    SSE         , &
    SPD         , &
    SCD         , &
    RPL         , &
    DDSDDT       (*), &
    DRPLDE       (*), &
    DRPLDT      , &
    STRAN        (*), &
    DSTRAN       (*), &
    TIME         (*), &
    DTIME       , &
    TEMP        , &
    DTEMP       , &
    PREDEF       (*), &
    DPRED        (*), &
    CMNAME      , &
    NDI         , &
    NSHR        , &
    NTENS       , &
    NSTATV      , &
    NPROPS      , &
    PROPS        (*), &
    COORDS       (*), &
    DROT         (*), &
    PNEWDT      , &
    CELENT      , &
    DFGRD0       (*), &
    DFGRD1       (*), &
    NOEL        , &
    NPT         , &
    LAYER       , &
    KSPT        , &
    KSTEP       , &
    KINC        , &

    )
    !-- Declarations (keep ABAQUS ABI names)
    REAL(wp), INTENT(INOUT) :: STRESS(*)
    REAL(wp), INTENT(INOUT) :: STATEV(*)
    REAL(wp), INTENT(OUT) :: DDSDDE(*)
    REAL(wp), INTENT(INOUT) :: SSE
    REAL(wp), INTENT(INOUT) :: SPD
    REAL(wp), INTENT(INOUT) :: SCD
    REAL(wp), INTENT(INOUT) :: RPL
    REAL(wp), INTENT(OUT) :: DDSDDT(*)
    REAL(wp), INTENT(OUT) :: DRPLDE(*)
    REAL(wp), INTENT(OUT) :: DRPLDT
    REAL(wp), INTENT(IN) :: STRAN(*)
    REAL(wp), INTENT(IN) :: DSTRAN(*)
    REAL(wp), INTENT(IN) :: TIME(*)
    REAL(wp), INTENT(IN) :: DTIME
    REAL(wp), INTENT(IN) :: TEMP
    REAL(wp), INTENT(IN) :: DTEMP
    REAL(wp), INTENT(IN) :: PREDEF(*)
    REAL(wp), INTENT(IN) :: DPRED(*)
    CHARACTER(LEN=80), INTENT(IN) :: CMNAME
    INTEGER(i4), INTENT(IN) :: NDI
    INTEGER(i4), INTENT(IN) :: NSHR
    INTEGER(i4), INTENT(IN) :: NTENS
    INTEGER(i4), INTENT(IN) :: NSTATV
    INTEGER(i4), INTENT(IN) :: NPROPS
    REAL(wp), INTENT(IN) :: PROPS(*)
    REAL(wp), INTENT(IN) :: COORDS(*)
    REAL(wp), INTENT(IN) :: DROT(*)
    REAL(wp), INTENT(OUT) :: PNEWDT
    REAL(wp), INTENT(IN) :: CELENT
    REAL(wp), INTENT(IN) :: DFGRD0(*)
    REAL(wp), INTENT(IN) :: DFGRD1(*)
    INTEGER(i4), INTENT(IN) :: NOEL
    INTEGER(i4), INTENT(IN) :: NPT
    INTEGER(i4), INTENT(IN) :: LAYER
    INTEGER(i4), INTENT(IN) :: KSPT
    INTEGER(i4), INTENT(IN) :: KSTEP
    INTEGER(i4), INTENT(IN) :: KINC


    !-- Local UFC TYPE instances (stack-allocated, no heap allocation)
    TYPE(MD_Mat_Base_Desc)  :: desc
    TYPE(MD_Mat_Base_State) :: state
    TYPE(MD_Mat_Base_Algo)  :: algo
    TYPE(PH_Mat_Base_Ctx)   :: ctx
    TYPE(RT_Com_Base_Ctx)   :: rt_ctx
    REAL(wp) :: pnewdt_buf

    !-- Local scalar buffers
    INTEGER(i4) :: kstep_local, kinc_local
    REAL(wp) :: step_time_local, total_time_local

    !---------------------------------------------------------------------------
    ! STEP 1: Pack ABAQUS parameters → UFC TYPE structures
    !---------------------------------------------------------------------------

    !-- [IN] Desc: material parameters (read-only, built at model load)
    desc%model_name       = cmname
    IF (ALLOCATED(desc%props)) DEALLOCATE(desc%props)
    ALLOCATE(desc%props(nprops))
    desc%props(1:nprops)  = props(1:nprops)
    desc%nprops            = nprops

    !-- [IN] Algo: pre-analysis solver configuration
    algo%ndi              = ndi
    algo%nshr             = nshr
    algo%ntens            = ntens
    algo%nstatv           = nstatv
    algo%integ_scheme     = 1_i4     ! implicit (UMAT default)
    algo%compute_tangent  = .TRUE.
    algo%use_algorithmic  = .FALSE.

    !-- [IN/OUT] State: material point state (updated in-place)
    state%stress(1:ntens)           = stress(1:ntens)
    state%statev(1:nstatv)          = statev(1:nstatv)
    state%ddsdde(1:ntens,1:ntens)   = ddsdde(1:ntens,1:ntens)
    state%sse = sse;  state%spd = spd;  state%scd = scd
    state%rpl  = rpl

    !-- [IN] Ctx: per-increment driving inputs
    ctx%stran(1:ntens)    = stran(1:ntens)
    ctx%dstran(1:ntens)   = dstran(1:ntens)
    step_time_local        = time(1)
    total_time_local       = time(2)
    ctx%step_time          = step_time_local
    ctx%total_time         = total_time_local
    ctx%dtime             = dtime
    ctx%temp              = temp
    ctx%dtemp             = dtemp
    ctx%coords(1:3)       = coords(1:3)
    ctx%drot(1:3,1:3)     = drot(1:3,1:3)
    ctx%celent            = celent
    ctx%dfgrd0(1:3,1:3)  = dfgrd0(1:3,1:3)
    ctx%dfgrd1(1:3,1:3)  = dfgrd1(1:3,1:3)
    kstep_local            = kstep
    kinc_local             = kinc
    ctx%kstep             = kstep_local
    ctx%kinc              = kinc_local
    ctx%elem_id           = noel
    ctx%gauss_pt          = npt
    ctx%layer             = layer
    ctx%kspt              = kspt

    !-- [RT] Runtime context
    rt_ctx%step_time      = step_time_local
    rt_ctx%total_time     = total_time_local
    rt_ctx%dtime          = dtime
    rt_ctx%kstep          = kstep_local
    rt_ctx%kinc           = kinc_local
    rt_ctx%elem_id        = noel
    rt_ctx%nlgeom         = (DFGRD0(1,1) /= 1.0_wp .OR. &
                               DFGRD0(2,2) /= 1.0_wp .OR. &
                               DFGRD0(3,3) /= 1.0_wp)
    rt_ctx%first_increment = (kinc == 1_i4)

    !-- pnewdt buffer
    pnewdt_buf = 1.0_wp  ! RT_PNEWDT_NO_CHANGE

    !---------------------------------------------------------------------------
    ! STEP 2: Call UFC native interface (replace with actual model call)
    !---------------------------------------------------------------------------
    ! CALL PH_Mat_UMAT_API(desc, ctx, state, algo, pnewdt_buf)
    ! Stub: replace with actual UFC native call when model is implemented
    ! Example:
    !   USE PH_Mat_UMAT_Mod, ONLY: PH_Mat_UMAT_API
    !   CALL PH_Mat_UMAT_API(desc, ctx, state, algo, rt_ctx, pnewdt_buf)

    !---------------------------------------------------------------------------
    ! STEP 3: Unpack UFC TYPE structures → ABAQUS flat arrays
    !---------------------------------------------------------------------------

    !-- [OUT] State → flat arrays
    stress(1:ntens)               = state%stress(1:ntens)
    statev(1:nstatv)              = state%statev(1:nstatv)
    ddsdde(1:ntens,1:ntens)       = state%ddsdde(1:ntens,1:ntens)
    sse  = state%sse;  spd = state%spd;  scd = state%scd
    rpl  = state%rpl
    ddsddt(1:ntens)               = state%ddsddt(1:ntens)
    drplde(1:ntens)               = state%drplde(1:ntens)
    drpldt                        = state%drpldt
    pnewdt                        = pnewdt_buf

  END SUBROUTINE UMAT

END MODULE PH_Mat_UMAT_Adapter_Mod
