!===================================================================
! MODULE:  MD_KW_Reg_Ext
! LAYER:   L3_MD
! DOMAIN:  KeyWord
! ROLE:    _Mgr
! BRIEF:   Extended keyword registry — supplements MD_KW_Reg.f90
!          with remaining critical Abaqus keywords identified
!          via KEYWORD.pdf audit (2026-05-05).
!===================================================================
MODULE MD_KW_Reg_Ext
  USE IF_Prec_Core, ONLY: wp, i4
  USE MD_KW_Def,    ONLY: KW_CAT_MODEL, KW_CAT_PART, KW_CAT_MESH, &
                          KW_CAT_MATERIAL, KW_CAT_SECTION, &
                          KW_CAT_CONSTRAINT, KW_CAT_LOAD, &
                          KW_CAT_CONTACT, KW_CAT_STEP, KW_CAT_OUTPUT, &
                          KW_CAT_AMPLITUDE, KW_CAT_SPECIAL, &
                          KW_CAT_END, KW_CAT_OTHER, &
                          PARAM_TYPE_STRING, PARAM_TYPE_INTEGER, &
                          PARAM_TYPE_REAL, PARAM_TYPE_ENUM, &
                          PARAM_TYPE_LOGICAL, PARAM_TYPE_NAME_REF
  USE MD_KW_Reg,    ONLY: kw_registry_register, kw_registry_add_param, &
                          kw_registry_set_data_spec
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: register_extended_keywords
CONTAINS
  SUBROUTINE register_extended_keywords()
    CALL register_connector_ext()
    CALL register_material_ext()
    CALL register_section_ext()
    CALL register_constraint_ext()
    CALL register_step_ext()
    CALL register_contact_ext()
    CALL register_load_ext()
    CALL register_mesh_ext()
    CALL register_ic_ext()
    CALL register_special_ext()
  END SUBROUTINE

  SUBROUTINE register_connector_ext()
    CALL kw_registry_register("CONNECTOR MOTION", KW_CAT_OTHER, "Connector motion")
    CALL kw_registry_add_param("CONNECTOR MOTION", "COMPONENT", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_add_param("CONNECTOR MOTION", "TYPE", PARAM_TYPE_ENUM, .TRUE.)
    CALL kw_registry_set_data_spec("CONNECTOR MOTION", .TRUE., cols=2)
    CALL kw_registry_register("CONNECTOR LOAD", KW_CAT_OTHER, "Connector loads")
    CALL kw_registry_add_param("CONNECTOR LOAD", "COMPONENT", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_set_data_spec("CONNECTOR LOAD", .TRUE., cols=2)
    CALL kw_registry_register("CONNECTOR STOP", KW_CAT_OTHER, "Connector stops")
    CALL kw_registry_add_param("CONNECTOR STOP", "COMPONENT", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_set_data_spec("CONNECTOR STOP", .TRUE., cols=2)
    CALL kw_registry_register("CONNECTOR LOCK", KW_CAT_OTHER, "Connector locking")
    CALL kw_registry_add_param("CONNECTOR LOCK", "COMPONENT", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_set_data_spec("CONNECTOR LOCK", .TRUE.)
    CALL kw_registry_register("CONNECTOR POTENTIAL", KW_CAT_OTHER, "Connector potential")
    CALL kw_registry_add_param("CONNECTOR POTENTIAL", "COMPONENT", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_set_data_spec("CONNECTOR POTENTIAL", .TRUE.)
    CALL kw_registry_register("CONNECTOR FAILURE", KW_CAT_OTHER, "Connector failure")
    CALL kw_registry_add_param("CONNECTOR FAILURE", "COMPONENT", PARAM_TYPE_INTEGER, .FALSE.)
    CALL kw_registry_set_data_spec("CONNECTOR FAILURE", .TRUE.)
    CALL kw_registry_register("CONNECTOR HARDENING", KW_CAT_OTHER, "Connector hardening")
    CALL kw_registry_add_param("CONNECTOR HARDENING", "COMPONENT", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_set_data_spec("CONNECTOR HARDENING", .TRUE., cols=2)
    CALL kw_registry_register("CONNECTOR UNIAXIAL BEHAVIOR", KW_CAT_OTHER, "Connector uniaxial behavior")
    CALL kw_registry_add_param("CONNECTOR UNIAXIAL BEHAVIOR", "COMPONENT", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_set_data_spec("CONNECTOR UNIAXIAL BEHAVIOR", .TRUE.)
    CALL kw_registry_register("FASTENER", KW_CAT_CONTACT, "Fasteners between surfaces")
    CALL kw_registry_add_param("FASTENER", "NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_add_param("FASTENER", "SURFACE", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_set_data_spec("FASTENER", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_material_ext()
    CALL kw_registry_register("DRUCKER PRAGER", KW_CAT_MATERIAL, "Drucker-Prager plasticity")
    CALL kw_registry_add_param("DRUCKER PRAGER", "SHEAR CRITERION", PARAM_TYPE_ENUM, .FALSE., "LINEAR")
    CALL kw_registry_add_param("DRUCKER PRAGER", "HARDENING", PARAM_TYPE_ENUM, .FALSE., "COMPRESSION")
    CALL kw_registry_set_data_spec("DRUCKER PRAGER", .TRUE.)
    CALL kw_registry_register("DRUCKER PRAGER HARDENING", KW_CAT_MATERIAL, "DP hardening")
    CALL kw_registry_set_data_spec("DRUCKER PRAGER HARDENING", .TRUE., cols=2)
    CALL kw_registry_register("MOHR COULOMB", KW_CAT_MATERIAL, "Mohr-Coulomb plasticity")
    CALL kw_registry_set_data_spec("MOHR COULOMB", .TRUE.)
    CALL kw_registry_register("CLAY HARDENING", KW_CAT_MATERIAL, "Clay hardening")
    CALL kw_registry_set_data_spec("CLAY HARDENING", .TRUE., cols=3)
    CALL kw_registry_register("CAP HARDENING", KW_CAT_MATERIAL, "Cap hardening")
    CALL kw_registry_set_data_spec("CAP HARDENING", .TRUE., cols=2)
    CALL kw_registry_register("CAST IRON COMPRESSION HARDENING", KW_CAT_MATERIAL, "CI compression hardening")
    CALL kw_registry_set_data_spec("CAST IRON COMPRESSION HARDENING", .TRUE., cols=2)
    CALL kw_registry_register("CAST IRON TENSION HARDENING", KW_CAT_MATERIAL, "CI tension hardening")
    CALL kw_registry_set_data_spec("CAST IRON TENSION HARDENING", .TRUE., cols=2)
    CALL kw_registry_register("FAILURE RATIOS", KW_CAT_MATERIAL, "Failure ratios")
    CALL kw_registry_set_data_spec("FAILURE RATIOS", .TRUE., cols=6)
    CALL kw_registry_register("SHEAR RETENTION", KW_CAT_MATERIAL, "Shear retention")
    CALL kw_registry_set_data_spec("SHEAR RETENTION", .TRUE., cols=2)
    CALL kw_registry_register("TENSILE FAILURE", KW_CAT_MATERIAL, "Tensile failure")
    CALL kw_registry_set_data_spec("TENSILE FAILURE", .TRUE., cols=1)
    CALL kw_registry_register("SHEAR FAILURE", KW_CAT_MATERIAL, "Shear failure")
    CALL kw_registry_set_data_spec("SHEAR FAILURE", .TRUE.)
    CALL kw_registry_register("SHEAR TEST DATA", KW_CAT_MATERIAL, "Shear test data")
    CALL kw_registry_set_data_spec("SHEAR TEST DATA", .TRUE.)
    CALL kw_registry_register("SIMPLE SHEAR TEST DATA", KW_CAT_MATERIAL, "Simple shear test data")
    CALL kw_registry_set_data_spec("SIMPLE SHEAR TEST DATA", .TRUE.)
    CALL kw_registry_register("UNIAXIAL TEST DATA", KW_CAT_MATERIAL, "Uniaxial test data")
    CALL kw_registry_set_data_spec("UNIAXIAL TEST DATA", .TRUE.)
    CALL kw_registry_register("BIAXIAL TEST DATA", KW_CAT_MATERIAL, "Biaxial test data")
    CALL kw_registry_set_data_spec("BIAXIAL TEST DATA", .TRUE.)
    CALL kw_registry_register("VOLUMETRIC TEST DATA", KW_CAT_MATERIAL, "Volumetric test data")
    CALL kw_registry_set_data_spec("VOLUMETRIC TEST DATA", .TRUE.)
    CALL kw_registry_register("COMBINED TEST DATA", KW_CAT_MATERIAL, "Combined test data")
    CALL kw_registry_set_data_spec("COMBINED TEST DATA", .TRUE.)
    CALL kw_registry_register("TRIAXIAL TEST DATA", KW_CAT_MATERIAL, "Triaxial test data")
    CALL kw_registry_set_data_spec("TRIAXIAL TEST DATA", .TRUE.)
    CALL kw_registry_register("RATE DEPENDENT", KW_CAT_MATERIAL, "Rate-dependent")
    CALL kw_registry_add_param("RATE DEPENDENT", "TYPE", PARAM_TYPE_ENUM, .FALSE., "POWER LAW")
    CALL kw_registry_set_data_spec("RATE DEPENDENT", .TRUE.)
    CALL kw_registry_register("HYSTERESIS", KW_CAT_MATERIAL, "Hysteresis")
    CALL kw_registry_set_data_spec("HYSTERESIS", .TRUE.)
    CALL kw_registry_register("MULLINS EFFECT", KW_CAT_MATERIAL, "Mullins effect")
    CALL kw_registry_set_data_spec("MULLINS EFFECT", .TRUE.)
    CALL kw_registry_register("CHARACTERISTIC LENGTH", KW_CAT_MATERIAL, "Char length")
    CALL kw_registry_set_data_spec("CHARACTERISTIC LENGTH", .TRUE.)
    CALL kw_registry_register("GASKET BEHAVIOR", KW_CAT_MATERIAL, "Gasket behavior")
    CALL kw_registry_add_param("GASKET BEHAVIOR", "NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("GASKET BEHAVIOR", .TRUE.)
    CALL kw_registry_register("SWELLING", KW_CAT_MATERIAL, "Swelling")
    CALL kw_registry_set_data_spec("SWELLING", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_section_ext()
    CALL kw_registry_register("SHELL GENERAL SECTION", KW_CAT_SECTION, "General shell")
    CALL kw_registry_add_param("SHELL GENERAL SECTION", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_add_param("SHELL GENERAL SECTION", "MATERIAL", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("SHELL GENERAL SECTION", "COMPOSITE", PARAM_TYPE_LOGICAL, .FALSE.)
    CALL kw_registry_set_data_spec("SHELL GENERAL SECTION", .TRUE.)
    CALL kw_registry_register("GASKET SECTION", KW_CAT_SECTION, "Gasket section")
    CALL kw_registry_add_param("GASKET SECTION", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_add_param("GASKET SECTION", "MATERIAL", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("GASKET SECTION", "SECTION", PARAM_TYPE_ENUM, .FALSE., "THICKNESS")
    CALL kw_registry_set_data_spec("GASKET SECTION", .TRUE.)
    CALL kw_registry_register("BEAM GENERAL SECTION", KW_CAT_SECTION, "General beam")
    CALL kw_registry_add_param("BEAM GENERAL SECTION", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_add_param("BEAM GENERAL SECTION", "MATERIAL", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_set_data_spec("BEAM GENERAL SECTION", .TRUE.)
    CALL kw_registry_register("BEAM SECTION OFFSET", KW_CAT_SECTION, "Beam offset")
    CALL kw_registry_add_param("BEAM SECTION OFFSET", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("BEAM SECTION OFFSET", .TRUE.)
    CALL kw_registry_register("SHEAR CENTER", KW_CAT_SECTION, "Shear center")
    CALL kw_registry_add_param("SHEAR CENTER", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("SHEAR CENTER", .TRUE., cols=2)
    CALL kw_registry_register("CENTROID", KW_CAT_SECTION, "Centroid")
    CALL kw_registry_add_param("CENTROID", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("CENTROID", .TRUE., cols=2)
    CALL kw_registry_register("TRANSVERSE SHEAR STIFFNESS", KW_CAT_SECTION, "Transv shear stiffness")
    CALL kw_registry_add_param("TRANSVERSE SHEAR STIFFNESS", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("TRANSVERSE SHEAR STIFFNESS", .TRUE.)
    CALL kw_registry_register("LAMINA", KW_CAT_SECTION, "Lamina")
    CALL kw_registry_set_data_spec("LAMINA", .TRUE., cols=6)
    CALL kw_registry_register("ELBOW", KW_CAT_SECTION, "Elbow pipe")
    CALL kw_registry_add_param("ELBOW", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("ELBOW", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_constraint_ext()
    CALL kw_registry_register("RIGID BODY", KW_CAT_CONSTRAINT, "Rigid body constraint")
    CALL kw_registry_add_param("RIGID BODY", "REF NODE", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("RIGID BODY", "ELEMENT SET", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("RIGID BODY", "PIN NSET", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("RIGID BODY", "TIE NSET", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_set_data_spec("RIGID BODY", .FALSE.)
    CALL kw_registry_register("PRE-TENSION SECTION", KW_CAT_CONSTRAINT, "Pre-tension bolt section")
    CALL kw_registry_add_param("PRE-TENSION SECTION", "NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_add_param("PRE-TENSION SECTION", "ELEMENT SET", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("PRE-TENSION SECTION", "NODE SET", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("PRE-TENSION SECTION", "SURFACE", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_set_data_spec("PRE-TENSION SECTION", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_step_ext()
    CALL kw_registry_register("HEAT TRANSFER", KW_CAT_STEP, "Heat transfer")
    CALL kw_registry_add_param("HEAT TRANSFER", "STEADY STATE", PARAM_TYPE_LOGICAL, .FALSE.)
    CALL kw_registry_add_param("HEAT TRANSFER", "DIRECT", PARAM_TYPE_LOGICAL, .FALSE.)
    CALL kw_registry_add_param("HEAT TRANSFER", "CETOL", PARAM_TYPE_REAL, .FALSE.)
    CALL kw_registry_set_data_spec("HEAT TRANSFER", .TRUE., cols=3)
    CALL kw_registry_register("COUPLED TEMPERATURE-DISPLACEMENT", KW_CAT_STEP, "Coupled thermal-stress")
    CALL kw_registry_add_param("COUPLED TEMPERATURE-DISPLACEMENT", "DIRECT", PARAM_TYPE_LOGICAL, .FALSE.)
    CALL kw_registry_add_param("COUPLED TEMPERATURE-DISPLACEMENT", "CEQ", PARAM_TYPE_REAL, .FALSE.)
    CALL kw_registry_set_data_spec("COUPLED TEMPERATURE-DISPLACEMENT", .TRUE., cols=4)
    CALL kw_registry_register("COUPLED THERMAL-ELECTRICAL", KW_CAT_STEP, "Coupled thermal-electrical")
    CALL kw_registry_add_param("COUPLED THERMAL-ELECTRICAL", "DIRECT", PARAM_TYPE_LOGICAL, .FALSE.)
    CALL kw_registry_set_data_spec("COUPLED THERMAL-ELECTRICAL", .TRUE., cols=3)
    CALL kw_registry_register("SUBCYCLING", KW_CAT_STEP, "Subcycling")
    CALL kw_registry_add_param("SUBCYCLING", "FACTOR", PARAM_TYPE_INTEGER, .FALSE., "10")
    CALL kw_registry_set_data_spec("SUBCYCLING", .FALSE.)
    CALL kw_registry_register("SOLUTION TECHNIQUE", KW_CAT_STEP, "Solution technique")
    CALL kw_registry_add_param("SOLUTION TECHNIQUE", "TYPE", PARAM_TYPE_ENUM, .TRUE.)
    CALL kw_registry_set_data_spec("SOLUTION TECHNIQUE", .FALSE.)
    CALL kw_registry_register("STEADY STATE TRANSPORT", KW_CAT_STEP, "Steady transport")
    CALL kw_registry_add_param("STEADY STATE TRANSPORT", "DIRECT", PARAM_TYPE_LOGICAL, .FALSE.)
    CALL kw_registry_set_data_spec("STEADY STATE TRANSPORT", .TRUE., cols=2)
    CALL kw_registry_register("RANDOM RESPONSE", KW_CAT_STEP, "Random response")
    CALL kw_registry_add_param("RANDOM RESPONSE", "SCALE", PARAM_TYPE_REAL, .FALSE.)
    CALL kw_registry_set_data_spec("RANDOM RESPONSE", .FALSE.)
  END SUBROUTINE

  SUBROUTINE register_contact_ext()
    CALL kw_registry_register("CONTACT INTERFERENCE", KW_CAT_CONTACT, "Contact interference")
    CALL kw_registry_add_param("CONTACT INTERFERENCE", "TYPE", PARAM_TYPE_ENUM, .FALSE., "SHRINK FIT")
    CALL kw_registry_set_data_spec("CONTACT INTERFERENCE", .TRUE.)
    CALL kw_registry_register("SLIDE LINE", KW_CAT_CONTACT, "Slide line contact")
    CALL kw_registry_add_param("SLIDE LINE", "TYPE", PARAM_TYPE_ENUM, .FALSE., "DEFORMABLE")
    CALL kw_registry_set_data_spec("SLIDE LINE", .TRUE.)
    CALL kw_registry_register("SHELL TO SOLID COUPLING", KW_CAT_CONTACT, "Shell-solid coupling")
    CALL kw_registry_add_param("SHELL TO SOLID COUPLING", "NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("SHELL TO SOLID COUPLING", .TRUE.)
    CALL kw_registry_register("FLEXIBLE JOINT", KW_CAT_CONTACT, "Flexible joint")
    CALL kw_registry_add_param("FLEXIBLE JOINT", "NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("FLEXIBLE JOINT", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_load_ext()
    CALL kw_registry_register("GRAVITY", KW_CAT_LOAD, "Gravity loading")
    CALL kw_registry_set_data_spec("GRAVITY", .TRUE., cols=4)
    CALL kw_registry_register("BASELINE CORRECTION", KW_CAT_LOAD, "Baseline correction")
    CALL kw_registry_set_data_spec("BASELINE CORRECTION", .TRUE.)
    CALL kw_registry_register("BASE MOTION", KW_CAT_LOAD, "Base motion")
    CALL kw_registry_add_param("BASE MOTION", "TYPE", PARAM_TYPE_ENUM, .TRUE.)
    CALL kw_registry_add_param("BASE MOTION", "DOF", PARAM_TYPE_INTEGER, .FALSE.)
    CALL kw_registry_set_data_spec("BASE MOTION", .FALSE.)
    CALL kw_registry_register("AQUA", KW_CAT_LOAD, "Fluid loading")
    CALL kw_registry_set_data_spec("AQUA", .TRUE.)
    CALL kw_registry_register("INCIDENT WAVE", KW_CAT_LOAD, "Incident wave")
    CALL kw_registry_add_param("INCIDENT WAVE", "TYPE", PARAM_TYPE_ENUM, .TRUE.)
    CALL kw_registry_set_data_spec("INCIDENT WAVE", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_mesh_ext()
    CALL kw_registry_register("REBAR LAYER", KW_CAT_MESH, "Rebar layers")
    CALL kw_registry_add_param("REBAR LAYER", "NAME", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_add_param("REBAR LAYER", "MATERIAL", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_set_data_spec("REBAR LAYER", .TRUE.)
    CALL kw_registry_register("DISPLAY BODY", KW_CAT_MESH, "Display body")
    CALL kw_registry_add_param("DISPLAY BODY", "ID", PARAM_TYPE_INTEGER, .TRUE.)
    CALL kw_registry_add_param("DISPLAY BODY", "ELEMENT SET", PARAM_TYPE_NAME_REF, .FALSE.)
    CALL kw_registry_set_data_spec("DISPLAY BODY", .FALSE.)
    CALL kw_registry_register("NORMAL", KW_CAT_MESH, "Normal direction")
    CALL kw_registry_add_param("NORMAL", "TYPE", PARAM_TYPE_ENUM, .FALSE., "ELEMENT")
    CALL kw_registry_set_data_spec("NORMAL", .TRUE.)
    CALL kw_registry_register("ADAPTIVE MESH", KW_CAT_MESH, "Adaptive mesh domain")
    CALL kw_registry_add_param("ADAPTIVE MESH", "ELSET", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_add_param("ADAPTIVE MESH", "TYPE", PARAM_TYPE_ENUM, .FALSE., "LAGRANGIAN")
    CALL kw_registry_set_data_spec("ADAPTIVE MESH", .FALSE.)
    CALL kw_registry_register("ADAPTIVE MESH CONSTRAINT", KW_CAT_MESH, "Adaptive mesh constraints")
    CALL kw_registry_add_param("ADAPTIVE MESH CONSTRAINT", "TYPE", PARAM_TYPE_ENUM, .TRUE.)
    CALL kw_registry_set_data_spec("ADAPTIVE MESH CONSTRAINT", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_ic_ext()
    CALL kw_registry_register("INITIAL CONDITIONS", KW_CAT_SPECIAL, "Initial conditions")
    CALL kw_registry_add_param("INITIAL CONDITIONS", "TYPE", PARAM_TYPE_ENUM, .TRUE.)
    CALL kw_registry_set_data_spec("INITIAL CONDITIONS", .TRUE.)
    CALL kw_registry_register("INITIAL STATE", KW_CAT_SPECIAL, "Initial state")
    CALL kw_registry_add_param("INITIAL STATE", "TYPE", PARAM_TYPE_ENUM, .FALSE., "STRESS")
    CALL kw_registry_add_param("INITIAL STATE", "FILE", PARAM_TYPE_STRING, .FALSE.)
    CALL kw_registry_set_data_spec("INITIAL STATE", .TRUE.)
  END SUBROUTINE

  SUBROUTINE register_special_ext()
    CALL kw_registry_register("CAVITY DEFINITION", KW_CAT_SPECIAL, "Cavity radiation")
    CALL kw_registry_add_param("CAVITY DEFINITION", "NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("CAVITY DEFINITION", .TRUE.)
    CALL kw_registry_register("REFLECTION", KW_CAT_SPECIAL, "Radiation symmetry")
    CALL kw_registry_add_param("REFLECTION", "NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("REFLECTION", .TRUE.)
    CALL kw_registry_register("WAVE", KW_CAT_SPECIAL, "Gravity waves")
    CALL kw_registry_set_data_spec("WAVE", .TRUE., cols=3)
    CALL kw_registry_register("WIND", KW_CAT_SPECIAL, "Wind profile")
    CALL kw_registry_set_data_spec("WIND", .TRUE., cols=2)
    CALL kw_registry_register("CONTOUR INTEGRAL", KW_CAT_SPECIAL, "Contour integral")
    CALL kw_registry_add_param("CONTOUR INTEGRAL", "CONTOURS", PARAM_TYPE_INTEGER, .FALSE., "4")
    CALL kw_registry_add_param("CONTOUR INTEGRAL", "CRACK NAME", PARAM_TYPE_NAME_REF, .TRUE.)
    CALL kw_registry_set_data_spec("CONTOUR INTEGRAL", .FALSE.)
    CALL kw_registry_register("CORRELATION", KW_CAT_SPECIAL, "Cross-correlation")
    CALL kw_registry_add_param("CORRELATION", "TYPE", PARAM_TYPE_ENUM, .TRUE.)
    CALL kw_registry_set_data_spec("CORRELATION", .TRUE.)
  END SUBROUTINE

END MODULE MD_KW_Reg_Ext
