#!/usr/bin/env python3
"""Export canonical MAT_* material variant catalog (scheme A).

SSOT for numeric IDs + Fortran symbols: L3 `MD_Mat_Ids.f90`.
L4 `PH_Mat_Reg.f90` re-exports the same `MAT_*` set (no duplicated PARAMETER lines).

Outputs (under docs/03_Domain_Pillars/MaterialPillar/):
  - material_variant_catalog.csv
  - material_variant_catalog_summary.md
  - material_l3_l4_mat_id_drift.md (only if mismatches)
"""

from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs" / "03_Domain_Pillars" / "MaterialPillar"

L3_PATH = ROOT / "ufc_core" / "L3_MD" / "Material" / "Contract" / "MD_Mat_Ids.f90"
L4_PATH = ROOT / "ufc_core" / "L4_PH" / "Material" / "PH_Mat_Reg.f90"
TEST_CLOSURE = ROOT / "tests" / "TEST_Material_L3_L4_Closure.f90"
TEST_RT_MAT = ROOT / "tests" / "L5_RT" / "RT_Mat_Test.f90"

# MD_Ana_Comp.f90 GROUP_MAT_COMPAT columns 1..11 (see file comments).
ANA_COMP_MAT_FAM_NAMES = (
    "Elastic",
    "Plastic",
    "Geo",
    "Hyper",
    "VE",
    "VP/Creep",
    "Damage",
    "Composite",
    "Heat/Thermal",
    "Acoustic",
    "EM/User",
)


@dataclass(frozen=True)
class MatConst:
    symbol: str
    value: int
    header: str
    source: str  # L3 or L4


HEADER_RE = re.compile(r"^\s*!\s*--\s*族\s*\d+\s*[:：]")


def _strip_fortran_comment(line: str) -> str:
    if "!" in line:
        return line.split("!", 1)[0]
    return line


def parse_mat_constants(path: Path, label: str) -> list[MatConst]:
    """Parse INTEGER PARAMETER blocks with MAT_* = <int> assignments."""
    text = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    current_header = ""
    rows: list[MatConst] = []
    for raw in text:
        line = raw.rstrip()
        if HEADER_RE.match(line):
            current_header = line.strip().lstrip("!").strip()
        stripped = _strip_fortran_comment(line)
        for sym, val in re.findall(r"\b(MAT_[A-Z0-9_]+)\s*=\s*(\d+)(?:_i4)?", stripped):
            rows.append(MatConst(symbol=sym, value=int(val), header=current_header, source=label))
    return rows


def mat_family_01_11(mat_id: int) -> int:
    """Map MAT_* numeric id to the 01..11 family index used in MD_Mat_Ids / PH_Mat_Reg.

    Note: acoustic constants live in the 1000-range (e.g. 1001) but are family **10**, not 100.
    """
    if 100 <= mat_id <= 199:
        return 1
    if 200 <= mat_id <= 299:
        return 2
    if 300 <= mat_id <= 399:
        return 3
    if 400 <= mat_id <= 499:
        return 4
    if 500 <= mat_id <= 599:
        return 5
    if 600 <= mat_id <= 699:
        return 6
    if 700 <= mat_id <= 799:
        return 7
    if 800 <= mat_id <= 899:
        return 8
    if 900 <= mat_id <= 999:
        return 9
    if 1000 <= mat_id <= 1099:
        return 10
    if 1100 <= mat_id <= 1199:
        return 11
    return 0


def ana_comp_column_for_mat_id(mat_id: int) -> tuple[int, str]:
    """Map MAT_* family (01..11) to GROUP_MAT_COMPAT material-family column (1..11)."""
    fam = mat_family_01_11(mat_id)
    if fam < 1:
        return 0, "OUT_OF_RANGE"
    return fam, ANA_COMP_MAT_FAM_NAMES[fam - 1]


def load_test_corpus() -> str:
    parts: list[str] = []
    for p in (TEST_CLOSURE, TEST_RT_MAT):
        if p.exists():
            parts.append(p.read_text(encoding="utf-8", errors="ignore"))
    return "\n".join(parts)


def write_drift_report(l3: dict[str, int], l4: dict[str, int]) -> Path | None:
    mismatches: list[tuple[str, int | None, int | None]] = []
    keys = sorted(set(l3) | set(l4))
    for k in keys:
        v3, v4 = l3.get(k), l4.get(k)
        if v3 is None or v4 is None or v3 != v4:
            mismatches.append((k, v3, v4))
    if not mismatches:
        return None
    out = OUT_DIR / "material_l3_l4_mat_id_drift.md"
    lines = [
        "# L3 vs L4 MAT_* ID drift",
        "",
        "Generated by `tools/material_mat_catalog.py`.",
        "",
        "Fix: align `MD_Mat_Ids.f90` and `PH_Mat_Reg.f90` so every `MAT_*` name/value pair matches.",
        "",
        "| symbol | L3 value | L4 value |",
        "|--------|----------|----------|",
    ]
    for sym, v3, v4 in mismatches:
        lines.append(f"| `{sym}` | {v3 if v3 is not None else '—'} | {v4 if v4 is not None else '—'} |")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def write_catalog(rows: list[dict[str, str]], drift_path: Path | None) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys()) if rows else []
    csv_path = OUT_DIR / "material_variant_catalog.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)

    summary_lines = [
        "# Material variant catalog (`MAT_*`)",
        "",
        "Generated by `tools/material_mat_catalog.py`.",
        "",
        "## Authority",
        "",
        "- Numeric IDs + Fortran symbols: `ufc_core/L3_MD/Material/Base/MD_Mat_BaseDef.f90`",
        "- L4 mirror (must match): `ufc_core/L4_PH/Material/Base/PH_Mat_Reg.f90`",
        "",
        f"- Rows: **{len(rows)}**",
    ]
    if drift_path:
        summary_lines.extend(
            [
                "",
                "## Drift",
                "",
                f"- **Mismatch detected** — see `{drift_path.relative_to(ROOT).as_posix()}`.",
            ]
        )
    else:
        summary_lines.extend(["", "## Drift", "", "- None detected (L3/L4 `MAT_*` name/value pairs match)."])
    (OUT_DIR / "material_variant_catalog_summary.md").write_text("\n".join(summary_lines) + "\n", encoding="utf-8")


def build_rows(l3_list: Iterable[MatConst], l4_map: dict[str, int], tests: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for m in sorted(l3_list, key=lambda x: (x.value, x.symbol)):
        fam = mat_family_01_11(m.value)
        col, cname = ana_comp_column_for_mat_id(m.value)
        v4 = l4_map.get(m.symbol)
        value_match = "Y" if v4 == m.value else "N"
        rows.append(
            {
                "mat_id_value": str(m.value),
                "mat_id_symbol": m.symbol,
                "ph_family_header": m.header,
                "mat_family_01_11": str(fam),
                "md_ana_comp_mat_fam_col": str(col),
                "md_ana_comp_mat_fam_name": cname,
                "l3_authority_file": L3_PATH.relative_to(ROOT).as_posix(),
                "l4_mirror_file": L4_PATH.relative_to(ROOT).as_posix(),
                "l3_l4_value_match": value_match,
                "mentioned_in_closure_or_rt_mat_tests": "Y" if m.symbol in tests else "N",
                "populate_status_note": "class_default_only; per-variant Populate routing not indexed here",
                "l5_route_status_note": "RT_Mat_Dispatch_Stress is validation stub (no per-MAT branch)",
                "l4_kernel_factory_note": "PH_Mat_Register_Kernel has no live registrations in tree scan",
            }
        )
    return rows


def main() -> None:
    l3_list = parse_mat_constants(L3_PATH, "L3")
    l4_list = parse_mat_constants(L4_PATH, "L4")
    l3_map = {m.symbol: m.value for m in l3_list}
    l4_map = {m.symbol: m.value for m in l4_list}
    # PH_Mat_Reg re-exports MAT_* from MD_Mat_Ids (no duplicate PARAMETER lines).
    if not l4_map and l3_map:
        l4_map = dict(l3_map)
    drift = write_drift_report(l3_map, l4_map)
    tests = load_test_corpus()
    rows = build_rows(l3_list, l4_map, tests)
    write_catalog(rows, drift)
    print(f"wrote {OUT_DIR / 'material_variant_catalog.csv'}")
    print(f"wrote {OUT_DIR / 'material_variant_catalog_summary.md'}")
    if drift:
        print(f"DRIFT: wrote {drift}")
    print(f"rows={len(rows)}")


if __name__ == "__main__":
    main()
