# -*- coding: utf-8 -*-
"""UFC 命名词表（单一真源）。

- ``LONG_NAME_ABBREV``：供 ``check_naming_l3l4l5l6.py`` 做模块名长词根检查；
  键为 PascalCase / 单词形态（与历史脚本一致）。
- ``verbose_token_hints()``：供 ``scan_verbose_identifiers.py`` 做局部标识符冗长词根扫描；
  返回 ``小写词根 -> 建议缩写``（消息用）。

新增/合并词根时**只改本文件**（`UFC/tools/naming_lexicon.py` 内 ``LONG_NAME_ABBREV``）。
"""

from __future__ import annotations

from typing import Dict

LONG_NAME_ABBREV: Dict[str, str] = {
    'Acceleration': 'Accel',
    'Accumulation': 'acc',
    'Adapter': 'Adapt',
    'Advanced': 'Adv',
    'Algorithm': 'Algo',
    'Alloy': 'Alloy',
    'Amplitude': 'Amp',
    'Anisotropic': 'Aniso',
    'ArrudaBoyce': 'AB',
    'Assembly': 'Assem',
    'Axial': 'Axial',
    'Barlat': 'Barlat',
    'Beam': 'Beam',
    'Bending': 'Bend',
    'BlatzKo': 'BK',
    'Boundary': 'Bdry',
    'Bridge': 'Brg',
    'Brittle': 'Brittle',
    'Builder': 'Bld',
    'Calculation': 'calc',
    'Chaboche': 'Chab',
    'Chain': 'Chain',
    'Change': 'Change',
    'Characteristic': 'Char_',
    'Coefficient': 'coef',
    'Command': 'Cmd',
    'Common': 'Common',
    'Complex': 'Cplx',
    'Composite': 'Comp',
    'Computation': 'comp',
    'Concentrated': 'Conc',
    'Concrete': 'Conc',
    'Conductance': 'Cond',
    'Conductivity': 'Cond',
    'Configuration': 'cfg',
    'Constitutive': 'Const',
    'Constraint': 'Constr',
    'Contact': 'Cont',
    'Coupling': 'Cpl',
    'Creep': 'Creep',
    'Damage': 'Dmg',
    'Damping': 'Damp',
    'Dashpot': 'Dash',
    'Decorator': 'Decor',
    'Demiray': 'Demiray',
    'Dense': 'Dense',
    'Director': 'Dir',
    'Displacement': 'Disp',
    'Distributed': 'Distrib',
    'Distribution': 'distrib',
    'Documentation': 'doc',
    'DruckerPrager': 'DP',
    'Elastic': 'Elas',
    'Electrorheological': 'ER',
    'Enforcement': 'Enforce',
    'Evaluation': 'Eval',
    'Extrapolation': 'extrap',
    'Factory': 'Fact',
    'Fatigue': 'Fatigue',
    'Fiber': 'Fiber',
    'Foam': 'Foam',
    'Foundations': 'Found',
    'Fracture': 'Frac',
    'Frequency': 'Freq',
    'Functionally': 'FGM',
    'Fung': 'Fung',
    'Gent': 'Gent',
    'Geomechanics': 'Geo',
    'Geometry': 'Geom',
    'Graded': 'FGM',
    'Growth': 'Growth',
    'Guccione': 'Guccione',
    'Gurson': 'Gurson',
    'Handler': 'Hdl',
    'Hashin': 'Hashin',
    'Helper': 'Help',
    'Hill': 'Hill',
    'HockettSherby': 'HS',
    'HolzapfelGasserOgden': 'HGO',
    'Hyperelastic': 'HyperElas',
    'Implementation': 'impl',
    'Inertia': 'Inertia',
    'Information': 'info',
    'Initialisation': 'Init',
    'Initialization': 'Init',
    'Initialize': 'Init',
    'Input': 'Inp',
    'Instance': 'Inst',
    'Integration': 'Integ',
    'Interface': 'Intf',
    'Interpolation': 'interp',
    'Isotropic': 'Iso',
    'Iterator': 'Iter',
    'JohnsonCook': 'JC',
    'Kelvin': 'Kelvin',
    'Laminated': 'Lam',
    'Layered': 'Layer',
    'Linear': 'Lin',
    'Longitudinal': 'Long',
    'Ludwik': 'Ludwik',
    'Magnetorheological': 'MR',
    'Magnetostrictive': 'Mag',
    'Management': 'mgr',
    'Mass': 'Mass',
    'Material': 'Mat',
    'Mathematical': 'Math',
    'Matrix': 'Mtx',
    'Maxwell': 'Maxwell',
    'Mediator': 'Med',
    'Membrane': 'Mem',
    'Memento': 'Mem',
    'Memory': 'Mem',
    'Metamaterial': 'Meta',
    'MohrCoulomb': 'MC',
    'MooneyRivlin': 'MR',
    'Multiscale': 'Multi',
    'NeoHookean': 'NH',
    'Nonlinear': 'Nonlin',
    'Nonstructural': 'NonStruct',
    'Observer': 'Obs',
    'Ogden': 'Ogden',
    'Orientation': 'Orient',
    'Orthotropic': 'Ortho',
    'Output': 'Out',
    'Parser': 'Parse',
    'Performance': 'perf',
    'Periodic': 'Period',
    'Phase': 'Phase',
    'Piezoelectric': 'Piezo',
    'Plastic': 'Plast',
    'Plasticity': 'Plast',
    'Point': 'Pt',
    'Porous': 'Porous',
    'Pressure': 'Press',
    'Projection': 'Proj',
    'Prony': 'Prony',
    'Properties': 'props',
    'Property': 'prop',
    'Prototype': 'Proto',
    'Proxy': 'Proxy',
    'Puck': 'Puck',
    'Radial': 'Radial',
    'Random': 'Rand',
    'Reconstruction': 'Recon',
    'Register': 'Reg',
    'Registry': 'Reg',
    'Reinforced': 'Reinf',
    'Remodeling': 'Remodel',
    'Residual': 'Res',
    'Response': 'Resp',
    'Rotary': 'Rot',
    'Sandwich': 'Sand',
    'Section': 'Sect',
    'Sensitivity': 'Sens',
    'Shape': 'Shape',
    'Shared': 'Shared',
    'Shear': 'Shear',
    'Shell': 'Shell',
    'Singleton': 'Single',
    'Solution': 'Solv',
    'Solver': 'Solv',
    'Sparse': 'Sparse',
    'Special': 'Spcl',
    'Spectrum': 'Spec',
    'Spring': 'Spring',
    'Standard': 'Std',
    'State': 'State',
    'Stiffness': 'Stiff',
    'Strain': 'Strain',
    'Strategy': 'Strat',
    'Stress': 'Stress',
    'Subsection': 'subsect',
    'Support': 'Supp',
    'Swift': 'Swift',
    'Temperature': 'Temp',
    'Template': 'Temp',
    'Thermal': 'Therm',
    'Thermoelectric': 'ThermElec',
    'TimeStep': 'Time',
    'Torsional': 'Tors',
    'Transformation': 'Trans',
    'Transverse': 'Trans',
    'Truss': 'Truss',
    'User': 'User',
    'Utilities': 'Util',
    'Utility': 'Util',
    'Utils': 'Util',
    'Validation': 'Valid',
    'VanDerWaals': 'VDW',
    'Vector': 'Vec',
    'Velocity': 'Vel',
    'Verification': 'Verif',
    'VerondaWestmann': 'VW',
    'Vibration': 'Vib',
    'Viscoelastic': 'Visc',
    'Viscoplastic': 'ViscPlast',
    'Visitor': 'Visit',
    'Voce': 'Voce',
    'Voigt': 'Voigt',
    'VonMises': 'VM',
    'Wrapper': 'Wrap',
    'Yeoh': 'Yeoh',
    'YoshidaUemori': 'YU',
    'ZerilliArmstrong': 'ZA'
}


def verbose_token_hints() -> Dict[str, str]:
    """Lowercase morpheme -> abbrev hint (scanner messages)."""
    out: Dict[str, str] = {}
    for k, v in LONG_NAME_ABBREV.items():
        if k.lower() == str(v).lower():
            continue
        out[k.lower()] = v
    return out
