!===============================================================================
! ADAPTER:  — ABAQUS  → UFC Native Interface
! Auto-generated by gen_umat_adapter.py — DO NOT EDIT MANUALLY
! Template: uel_adapter.f90.j2
! Reference: ABAQUS_Subroutine_UFC_TYPE_Mapping.md §3
! Generated: 2026-04-13T15:30:33Z
!
! PURPOSE:
!   ABAQUS  flat-parameter interface
!     → pack into UFC TYPE structures
!     → call UFC native interface (PH_Elem_UEL_API)
!     → unpack results back to ABAQUS flat arrays (RHS, AMATRX)
!
! DESIGN RULES:
!   ✓ Flat arrays ONLY in this adapter
!   ✓ All ABAQUS params packed into Desc/State/Algo/Ctx TYPEs
!   ✓ UFC native side uses typed structs exclusively
!   ✓ LFLAGS determines AMATRX physical meaning (stiffness/mass/damping)
!
! UEL vs UMAT key differences:
!   - UEL is called per ELEMENT (not per material point)
!   - UEL receives element nodal DOFs and computes RHS/AMATRX
!   - Element-level state stored in PH_Elem_Base_State % svars(:)
!   - Material call inside UEL: multi-IP svars slice → PH_XXX_UMAT_API per IP
!
! USAGE:
!   1. Copy generated file to: UFC/ufc_core/L4_PH/Element/Adapters/
!   2. Rename  →  (keep ABAQUS ABI)
!   3. USE UFC native module: USE PH_Elem_UEL_Mod
!   4. Call PH_Elem_UEL_API per element (not per material point)
!
! PARAMETER MAP:

!   RHS          →                                      ! [OUT]

!   AMATRX       →                                      ! [OUT]

!   SVARS        →                                      ! [IN/OUT]

!    ENERGY      →                                      ! [OUT]

!   JDLTYP       →                                      ! [IN]

!   KSTEP        →                                      ! [IN]

!   KINC         →                                      ! [IN]

!   JELEM        →                                      ! [IN]

!   TIME         →                                      ! [IN]

!   DTIME        →                                      ! [IN]

!   NODE         →                                      ! [IN]

!   JDOF         →                                      ! [IN]

!   JTYPE        →                                      ! [IN]

!   NNODE        →                                      ! [IN]

!   NDOFEL       →                                      ! [IN]

!   NRHS         →                                      ! [IN]

!   NSYMM        →                                      ! [IN]

!   MLVARX       →                                      ! [IN]

!   NDLOAD       →                                      ! [IN]

!   JDLTYP       →                                      ! [IN]

!   PERIOD       →                                      ! [IN]

!   LFLAGS       →                                      ! [IN]

!   JPROPS       →                                      ! [IN]

!   NJPROP       →                                      ! [IN]

!   NPROPS       →                                      ! [IN]

!   PROPS        →                                      ! [IN]

!   COORDS       →                                      ! [IN]

!   NTENS        →                                      ! [IN]

!   NSTATV       →                                      ! [IN]

!   NOEL         →                                      ! [IN]

!   NPT          →                                      ! [IN]

!   KSPT         →                                      ! [IN]

!   KSPG         →                                      ! [IN]

!   NLAYER       →                                      ! [IN]

!   NPTT         →                                      ! [IN]

!   JSTEP        →                                      ! [IN]

!   JINCR        →                                      ! [IN]

!   QUERY        →                                      ! [IN]

!   V            →                                      ! [IN]

!   U            →                                      ! [IN]

!   DU           →                                      ! [IN]

!   A            →                                      ! [IN]

!   PREDEF       →                                      ! [IN]

!   DPRED        →                                      ! [IN]

!   CMAUR        →                                      ! [IN]

!   NDLJD        →                                      ! [IN]

!   MDLtyp       →                                      ! [IN]

!   JDLJDs       →                                      ! [IN]

!   DLJDF        →                                      ! [IN]

!   SNRM         →                                      ! [OUT]

!   PNEWDT       →                                      ! [OUT]

!   NFLUX        →                                      ! [IN]

!   DKDG         →                                      ! [OUT]

!   SCON         →                                      ! [OUT]

!===============================================================================
MODULE PH_Elem_UEL_Adapter_Mod
  USE IF_Prec_Core,     ONLY: wp, i4
  !-- UFC TYPEs: L3_MD
  USE MD_Elem_Types, ONLY: &
    MD_Elem_Base_Desc,   &  ! Element topology and properties
    MD_Elem_Base_Algo,   &  ! Pre-analysis config (integ_scheme, etc.)
    MD_Elem_Base_State       ! Element-level state (svars)
  USE MD_Mat_Types, ONLY: &
    MD_Mat_Base_Desc,    &  ! Material parameters (for embedded mat call)
    MD_Mat_Base_State,   &  ! Material state
    MD_Mat_Base_Algo        ! Material config
  !-- UFC TYPEs: L4_PH
  USE PH_Elem_Types, ONLY: &
    PH_Elem_Base_Ctx,   &  ! Per-increment element context
    PH_Elem_Base_State, &  ! Element outputs (RHS, AMATRX, energy)
    PH_Elem_Base_Algo       ! Newton iteration control
  USE PH_Mat_Types, ONLY: &
    PH_Mat_Base_Ctx,    &  ! Per-IP material context
    PH_Mat_Base_Algo        ! Material iteration control
  !-- UFC TYPEs: L5_RT
  USE RT_Com_Types, ONLY: RT_Com_Base_Ctx
  IMPLICIT NONE
  PRIVATE

  PUBLIC :: 

CONTAINS

  !============================================================================
  !  — ABAQUS  Interface Adapter
  !
  ! UEL = User ELEMENT. Called once per element per iteration.
  !
  ! Key differences from UMAT adapter:
  !   - NDOFEL: total DOFs for this element (not NTENS)
  !   - RHS(NDOFEL, NRHS): residual vector (not stress)
  !   - AMATRX(NDOFEL, NDOFEL): tangent stiffness/mass/damping matrix
  !   - LFLAGS(6): controls what to form (stiffness/mass/damping/bulk)
  !   - Element state in svars(:) — must slice per IP for material calls
  !============================================================================
  SUBROUTINE ( &

    RHS,          

    AMATRX,       

    SVARS,        

     ENERGY,      

    JDLTYP,       

    KSTEP,        

    KINC,         

    JELEM,        

    TIME,         

    DTIME,        

    NODE,         

    JDOF,         

    JTYPE,        

    NNODE,        

    NDOFEL,       

    NRHS,         

    NSYMM,        

    MLVARX,       

    NDLOAD,       

    JDLTYP,       

    PERIOD,       

    LFLAGS,       

    JPROPS,       

    NJPROP,       

    NPROPS,       

    PROPS,        

    COORDS,       

    NTENS,        

    NSTATV,       

    NOEL,         

    NPT,          

    KSPT,         

    KSPG,         

    NLAYER,       

    NPTT,         

    JSTEP,        

    JINCR,        

    QUERY,        

    V,            

    U,            

    DU,           

    A,            

    PREDEF,       

    DPRED,        

    CMAUR,        

    NDLJD,        

    MDLtyp,       

    JDLJDs,       

    DLJDF,        

    SNRM,         

    PNEWDT,       

    NFLUX,        

    DKDG,         

    SCON,         

    )
    !-- Keep ABAQUS ABI names

    
    REAL(wp), INTENT(OUT) :: RHS(*)
    

    
    REAL(wp), INTENT(OUT) :: AMATRX(*)
    

    
    REAL(wp), INTENT(INOUT) :: SVARS(*)
    

    
    REAL(wp), INTENT(OUT) ::  ENERGY(*)
    

    
    INTEGER(i4), INTENT(IN) :: JDLTYP(*)
    

    
    INTEGER(i4), INTENT(IN) :: KSTEP
    

    
    INTEGER(i4), INTENT(IN) :: KINC
    

    
    INTEGER(i4), INTENT(IN) :: JELEM
    

    
    REAL(wp), INTENT(IN) :: TIME(*)
    

    
    REAL(wp), INTENT(IN) :: DTIME
    

    
    INTEGER(i4), INTENT(IN) :: NODE(*)
    

    
    INTEGER(i4), INTENT(IN) :: JDOF(*)
    

    
    INTEGER(i4), INTENT(IN) :: JTYPE
    

    
    INTEGER(i4), INTENT(IN) :: NNODE
    

    
    INTEGER(i4), INTENT(IN) :: NDOFEL
    

    
    INTEGER(i4), INTENT(IN) :: NRHS
    

    
    INTEGER(i4), INTENT(IN) :: NSYMM
    

    
    INTEGER(i4), INTENT(IN) :: MLVARX
    

    
    INTEGER(i4), INTENT(IN) :: NDLOAD
    

    
    INTEGER(i4), INTENT(IN) :: JDLTYP(*)
    

    
    REAL(wp), INTENT(IN) :: PERIOD
    

    
    INTEGER(i4), INTENT(IN) :: LFLAGS(*)
    

    
    INTEGER(i4), INTENT(IN) :: JPROPS(*)
    

    
    INTEGER(i4), INTENT(IN) :: NJPROP
    

    
    INTEGER(i4), INTENT(IN) :: NPROPS
    

    
    REAL(wp), INTENT(IN) :: PROPS(*)
    

    
    REAL(wp), INTENT(IN) :: COORDS(*)
    

    
    INTEGER(i4), INTENT(IN) :: NTENS
    

    
    INTEGER(i4), INTENT(IN) :: NSTATV
    

    
    INTEGER(i4), INTENT(IN) :: NOEL
    

    
    INTEGER(i4), INTENT(IN) :: NPT
    

    
    INTEGER(i4), INTENT(IN) :: KSPT
    

    
    INTEGER(i4), INTENT(IN) :: KSPG
    

    
    INTEGER(i4), INTENT(IN) :: NLAYER
    

    
    INTEGER(i4), INTENT(IN) :: NPTT
    

    
    INTEGER(i4), INTENT(IN) :: JSTEP
    

    
    INTEGER(i4), INTENT(IN) :: JINCR
    

    
    INTEGER(i4), INTENT(IN) :: QUERY
    

    
    REAL(wp), INTENT(IN) :: V(*)
    

    
    REAL(wp), INTENT(IN) :: U(*)
    

    
    REAL(wp), INTENT(IN) :: DU(*)
    

    
    REAL(wp), INTENT(IN) :: A(*)
    

    
    REAL(wp), INTENT(IN) :: PREDEF(*)
    

    
    REAL(wp), INTENT(IN) :: DPRED(*)
    

    
    INTEGER(i4), INTENT(IN) :: CMAUR
    

    
    INTEGER(i4), INTENT(IN) :: NDLJD
    

    
    INTEGER(i4), INTENT(IN) :: MDLtyp(*)
    

    
    INTEGER(i4), INTENT(IN) :: JDLJDs(*)
    

    
    REAL(wp), INTENT(IN) :: DLJDF(*)
    

    
    REAL(wp), INTENT(OUT) :: SNRM
    

    
    REAL(wp), INTENT(INOUT) :: PNEWDT
    

    
    INTEGER(i4), INTENT(IN) :: NFLUX
    

    
    REAL(wp), INTENT(OUT) :: DKDG(*)
    

    
    REAL(wp), INTENT(OUT) :: SCON(*)
    


    !-- Local UFC TYPE instances
    TYPE(MD_Elem_Base_Desc)  :: elem_desc
    TYPE(MD_Elem_Base_State)  :: elem_state
    TYPE(PH_Elem_Base_Ctx)   :: elem_ctx
    TYPE(PH_Elem_Base_State)  :: elem_state_out
    TYPE(RT_Com_Base_Ctx)     :: rt_ctx
    REAL(wp) :: pnewdt_buf

    !-- Local buffers
    INTEGER(i4) :: nsvars_per_ip, n_ips, ip
    REAL(wp), ALLOCATABLE :: coords_buf(:,:), u_buf(:)
    CHARACTER(LEN=80) :: cmname_local

    !---------------------------------------------------------------------------
    ! STEP 1: Pack ABAQUS parameters → UFC TYPE structures
    !---------------------------------------------------------------------------

    !-- [IN] Element Desc
    elem_desc%elem_id   = jelem
    elem_desc%jtype     = jtype
    elem_desc%nnode     = nnode
    elem_desc%ndofel    = ndofel
    elem_desc%nprops     = nprops
    IF (ALLOCATED(elem_desc%props)) DEALLOCATE(elem_desc%props)
    ALLOCATE(elem_desc%props(nprops))
    elem_desc%props(1:nprops) = props(1:nprops)

    !-- [IN] Element Algo (from LFLAGS: what to form)
    elem_desc%integ_scheme = 1_i4  ! default: Gauss
    IF (ALLOCATED(elem_desc%jdltyp)) DEALLOCATE(elem_desc%jdltyp)
    IF (njprop > 0) THEN
      ALLOCATE(elem_desc%jdltyp(njprop))
      elem_desc%jdltyp(1:njprop) = jprops(1:njprop)
    END IF

    !-- [IN/OUT] Element State (svars slice — must be preserved between IPs)
    elem_state%svars(1:nsvars) = svars(1:nsvars)

    !-- [IN] Element Ctx (nodal coords, DOFs, etc.)
    ! coords_buf: reshape COORDS from 1D (3*NNODE) to 2D (3, NNODE)
    IF (ALLOCATED(coords_buf)) DEALLOCATE(coords_buf)
    ALLOCATE(coords_buf(3, nnode))
    DO ip = 1, nnode
      coords_buf(1:3, ip) = coords(3*(ip-1)+1 : 3*ip)
    END DO
    elem_ctx%coords => coords_buf

    ! u/du: displacement buffers
    IF (ALLOCATED(u_buf)) DEALLOCATE(u_buf)
    ALLOCATE(u_buf(ndofel))
    u_buf(1:ndofel) = v(1:ndofel)
    elem_ctx%u => u_buf

    ! Time / increment context
    elem_ctx%step_time  = time(1)
    elem_ctx%total_time = time(2)
    elem_ctx%dtime      = dtime
    elem_ctx%kstep      = kstep
    elem_ctx%kinc       = kinc
    elem_ctx%elem_id    = jelem
    elem_ctx%nlgeom     = (lflags(1) == 2_i4)  ! mass matrix = NLGEOM

    ! LFLAGS decode:
    !   LFLAGS(1)=1: form stiffness   → AMATRX = K_e
    !   LFLAGS(1)=2: form mass        → AMATRX = M_e
    !   LFLAGS(1)=4: form damping     → AMATRX = C_e
    !   LFLAGS(1)=5: form bulk modulus → AMATRX = B_e
    elem_ctx%lflags(1:6) = lflags(1:6)

    !-- [RT] Runtime context
    rt_ctx%step_time   = time(1)
    rt_ctx%total_time  = time(2)
    rt_ctx%dtime       = dtime
    rt_ctx%kstep       = kstep
    rt_ctx%kinc        = kinc
    rt_ctx%elem_id     = jelem
    rt_ctx%nlgeom      = elem_ctx%nlgeom
    rt_ctx%first_increment = (kinc == 1_i4)

    pnewdt_buf = 1.0_wp

    !---------------------------------------------------------------------------
    ! STEP 2: Call UFC native element interface
    !---------------------------------------------------------------------------
    ! CALL PH_Elem_UEL_API(elem_desc, elem_ctx, elem_state_out, pnewdt_buf)
    ! Stub: replace with actual UFC native call

    !---------------------------------------------------------------------------
    ! STEP 3: Unpack UFC TYPE structures → ABAQUS flat arrays
    !---------------------------------------------------------------------------

    !-- [OUT] RHS (residual vector)
    rhs(1:ndofel, 1:nrhs) = elem_state_out%rhs(1:ndofel, 1:nrhs)

    !-- [OUT] AMATRX (stiffness / mass / damping — determined by LFLAGS)
    !   NOTE: ABAQUS expects full AMATRX; Fortran is column-major
    amatrx(1:ndofel, 1:ndofel) = elem_state_out%amatrx(1:ndofel, 1:ndofel)

    !-- [OUT] Energy
    energy(1:8) = elem_state_out%energy(1:8)

    !-- [IN/OUT] Element state (persisted svars — slice per IP for mat calls)
    svars(1:nsvars) = elem_state_out%svars(1:nsvars)

    !-- pnewdt: take minimum across IPs
    pnewdt = pnewdt_buf

  END SUBROUTINE 

END MODULE PH_Elem_UEL_Adapter_Mod
